---
- name: Enable unattended upgrades
  include_tasks: enable.yml
  when:
    - item.distribution == ansible_distribution
    - item.version == ansible_distribution_major_version
  with_items: "{{ unattended_upgrades_enable_for }}"
  loop_control:
    label: "{{ ansible_distribution }}:{{ ansible_distribution_major_version }}"

- name: Disable unattended upgrades
  include_tasks: disable.yml
  when:
    - item.distribution == ansible_distribution
    - item.version == ansible_distribution_major_version
  with_items: "{{ unattended_upgrades_disable_for }}"
  loop_control:
    label: "{{ ansible_distribution }}:{{ ansible_distribution_major_version }}"
